spring.application.name=raghoulwave_yt_bot
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

raghoulwavebot.config.webhook.url=
raghoulwavebot.config.webhook.token=
raghoulwavebot.config.administrator.id=

raghoulwavebot.config.spotify.client_id=
raghoulwavebot.config.spotify.client_secret=
raghoulwavebot.config.spotify.redirect_uri=

raghoulwavebot.config.ytdlp.download-dir=
raghoulwavebot.config.google.youtube_data_api_v3.api_key=